version: "3.7"
services:
  # building service 1 and DB
  service1:
    build: ./service1
    image: docker.io/sch0tterfoinfoin/service1
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
    deploy:
      replicas: 2
    environment:
      DATABASE_URI: ${DATABASE_URI}
      SECRET_KEY: ${SECRET_KEY}
  # building service 2
  service2: 
    build: ./service2
    image: docker.io/sch0tterfoinfoin/service2
    ports: 
      - target: 5001
        published: 5001
        protocol: tcp
    deploy:
      replicas: 2
  # building service 3
  service3: 
    build: ./service3
    image: docker.io/sch0tterfoinfoin/service3
    ports: 
      - target: 5002
        published: 5002
        protocol: tcp
    deploy:
      replicas: 2
  # building service 4
  service4: 
    build: ./service4
    image: docker.io/sch0tterfoinfoin/service4
    ports: 
      - target: 5003
        published: 5003
        protocol: tcp
    deploy:
      replicas: 2
  # building database variables using .env
#   database:
#     image: mysql:5.7
#     ports:
#       - target: 3306
#         published: 3306
#     environment:
#       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#       MYSQL_DATABASE: emaildb
#     volumes:
#       - type: volume
#         source: database-volume
#         target: /var/lib/mysql
# volumes:
#   database-volume: