version: "3.7"
services: 
	service1: 
		nginx:
		image: nginx:alpine
		ports: 
			target: 5000
			published: 5000
			protocol: tcp
		environment:
			DATABASE_URI: ${mysql+pymysql://root:root@35.246.94.253:3306/emaildb}
			SECRET_KEY: ${fasdfadsfadsfwaefsadv43tw4}
			TEST_DATABASE_URI: ${mysql+pymysql://root:root@35.246.94.253:3306/emaildbtest}
			TEST_SECRET_KEY: ${fasdfadsfadsfwaefsadv43tw4}

	services2: 
		nginx:
		image: nginx:alpine
		ports: 
			target: 5001
			published: 5001
			protocol: tcp 
	service3: 
		nginx:
		image: nginx:alpine
		ports: 
			target: 5002
			published: 5002
			protocol: tcp
	service4: 
		nginx:
		image: nginx:alpine
		ports: 
			target: 5003
			published: 5003
	 		protocol: tcp